spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    username: sa
    url: jdbc:h2:mem:mingledb
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 9000
