spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mingledb
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
server:
  port: 9000
